# Generated by Django 5.1.1 on 2024-10-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_customuser_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
