# Generated by Django 5.1.1 on 2024-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_customuser_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="encryption_key",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
