# Generated by Django 5.1.1 on 2024-10-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0005_customuser_encryption_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="encryption_key",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_code/"),
        ),
    ]
