# Generated by Django 5.1.1 on 2024-10-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0006_remove_customuser_encryption_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
