# Generated by Django 5.1.2 on 2024-10-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='type_transference',
            field=models.CharField(choices=[('SEND', 'send'), ('RELOAD', 'reload'), ('REQUEST', 'request')], max_length=100),
        ),
    ]
