# Generated by Django 5.1.1 on 2024-09-21 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_user_alter_wallet_user_delete_usuarioprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.user'),
        ),
    ]
