# Generated by Django 5.1.1 on 2024-09-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_transference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transference',
        ),
    ]
