# Generated by Django 5.1.1 on 2024-09-28 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_transference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
