# Generated by Django 5.1.2 on 2024-10-22 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_userpayment_delete_transference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='app_user',
            new_name='id_wallet',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
