# Generated by Django 5.1.1 on 2024-11-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0014_rename_app_user_userpayment_id_wallet_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
